# Generated by Django 5.1 on 2024-08-25 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_aboutview_options_contact_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutView',
            new_name='About',
        ),
    ]
